[package]
name = "salad"
description = "salad generates random passphrases from a word-list for *nix systems."
version = "0.1.0"
authors = ["crawlingChaos"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
